import { Command } from 'commander';
import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs';
import path from 'path';

// â”€â”€â”€ Legacy raw-YAML templates â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

const DEPLOY_WORKFLOW = `# Generated by Hylius CLI
# Docs: https://github.com/isaac-hash/hylius
#
# Required GitHub Secrets:
#   HYLIUS_HOST       - Your VPS IP address
#   HYLIUS_USER       - SSH username (e.g., root)
#   HYLIUS_SSH_KEY    - Full SSH private key content
#   HYLIUS_TARGET_PATH - Remote deploy path (e.g., /var/www/my-app)
#   HYLIUS_REPO_URL   - Git repository URL (https://github.com/user/repo.git)
#
# Optional Secrets:
#   HYLIUS_PASSWORD   - SSH password (only if not using keys)
#   HYLIUS_PORT       - SSH port (defaults to 22)

name: Deploy with Hylius

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy with Hylius
        run: npx hylius deploy
        env:
          CI: 'true'
          HYLIUS_HOST: \${{ secrets.HYLIUS_HOST }}
          HYLIUS_USER: \${{ secrets.HYLIUS_USER }}
          HYLIUS_SSH_KEY: \${{ secrets.HYLIUS_SSH_KEY }}
          HYLIUS_PASSWORD: \${{ secrets.HYLIUS_PASSWORD }}
          HYLIUS_PORT: \${{ secrets.HYLIUS_PORT }}
          HYLIUS_TARGET_PATH: \${{ secrets.HYLIUS_TARGET_PATH }}
          HYLIUS_REPO_URL: \${{ secrets.HYLIUS_REPO_URL }}
          HYLIUS_BRANCH: \${{ github.ref_name }}
`;

const FULL_PIPELINE_WORKFLOW = `# Generated by Hylius CLI â€” Full Pipeline (Setup + Deploy)
# Docs: https://github.com/isaac-hash/hylius

name: Hylius Full Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      run_setup:
        description: 'Run server provisioning (hylius setup)?'
        type: boolean
        default: false

env:
  CI: 'true'
  HYLIUS_HOST: \${{ secrets.HYLIUS_HOST }}
  HYLIUS_USER: \${{ secrets.HYLIUS_USER }}
  HYLIUS_SSH_KEY: \${{ secrets.HYLIUS_SSH_KEY }}
  HYLIUS_PASSWORD: \${{ secrets.HYLIUS_PASSWORD }}
  HYLIUS_PORT: \${{ secrets.HYLIUS_PORT }}
  HYLIUS_TARGET_PATH: \${{ secrets.HYLIUS_TARGET_PATH }}
  HYLIUS_REPO_URL: \${{ secrets.HYLIUS_REPO_URL }}
  HYLIUS_BRANCH: \${{ github.ref_name }}

jobs:
  setup:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_setup == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: Provision Server
        run: npx hylius setup

  deploy:
    runs-on: ubuntu-latest
    needs: [setup]
    if: always() && (needs.setup.result == 'success' || needs.setup.result == 'skipped')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy with Hylius
        run: npx hylius deploy
`;

// â”€â”€â”€ Dagger module file templates â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

const DAGGER_WORKFLOW_YAML = (branch: string) => `name: Hylius Dagger CI

on:
  push:
    branches: [${branch}]
  pull_request:
    branches: [${branch}]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "\${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u \${{ github.actor }} --password-stdin

      - name: Fetch Build Env from Hylius Dashboard
        id: fetch-env
        run: |
          if [ -n "\${{ secrets.HYLIUS_WEBHOOK_URL }}" ]; then
            HYLIUS_BASE_URL=$(echo "\${{ secrets.HYLIUS_WEBHOOK_URL }}" | sed 's|/api/webhooks/deploy-complete||')
            curl -s -f -H "Authorization: Bearer \${{ secrets.HYLIUS_API_TOKEN }}" \\
              "$HYLIUS_BASE_URL/api/webhooks/env?repo=\${{ github.repository }}" > .hylius.env || true
          fi
          
          if [ -s .hylius.env ]; then
            grep -v '^#' .hylius.env | awk 'NF' >> \$GITHUB_ENV
            echo "Build env vars fetched and exported successfully"
          fi

      # ── Path A: Dockerfile exists → use Dagger ──
      - name: Build & push via Dagger (Dockerfile found)
        if: hashFiles('Dockerfile') != ''
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          args: build-and-push --source=. --registry=ghcr.io --image=ghcr.io/\${{ github.repository }} --tag=\${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.sha }} --webhook-url=\${{ secrets.HYLIUS_WEBHOOK_URL }} --webhook-token=\${{ secrets.HYLIUS_API_TOKEN }} --repo=\${{ github.repository }} --sha=\${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }} --ref=\${{ github.ref }} --pr-number="\${{ github.event.pull_request.number }}" --github-token=env:GITHUB_TOKEN
          module: .dagger
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      # ── Path B: No Dockerfile → use Railpack natively ──
      - name: Set up Docker Buildx
        if: hashFiles('Dockerfile') == ''
        uses: docker/setup-buildx-action@v3

      - name: Build & push image with Railpack (no Dockerfile)
        if: hashFiles('Dockerfile') == ''
        run: |
          echo "No Dockerfile found — installing Railpack..."
          curl -sSL https://railpack.com/install.sh | bash
          
          # Load env vars if fetched
          RAILPACK_ENV_ARGS=""
          SECRET_ARGS=""
          if [ -s .hylius.env ]; then
            while IFS= read -r line; do
              [[ "\$line" =~ ^#.*$ || -z "\$line" ]] && continue
              # Extract KEY out of KEY=VALUE
              KEY=$(echo "\$line" | cut -d '=' -f 1)
              RAILPACK_ENV_ARGS="\$RAILPACK_ENV_ARGS --env \$KEY"
              SECRET_ARGS="\$SECRET_ARGS --secret id=\$KEY,env=\$KEY"
            done < .hylius.env
          fi

          IMAGE_TAG=\${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.sha }}
          IMAGE_FULL="ghcr.io/\${{ github.repository }}:$IMAGE_TAG"
          IMAGE_FULL=$(echo "$IMAGE_FULL" | tr '[:upper:]' '[:lower:]')

          # Generate Railpack build plan
          railpack prepare \$RAILPACK_ENV_ARGS --plan-out /tmp/railpack-plan.json .

          # Build and push using docker buildx with the generated plan
          docker buildx build \\
            --build-arg BUILDKIT_SYNTAX=ghcr.io/railwayapp/railpack-frontend \\
            -f /tmp/railpack-plan.json \\
            \$SECRET_ARGS \\
            --tag "\$IMAGE_FULL" \\
            --push \\
            .
          
          echo "Pushed \$IMAGE_FULL"
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Notify Hylius Dashboard
        if: hashFiles('Dockerfile') == ''
        run: |
          IMAGE_TAG=\${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.sha }}
          IMAGE_FULL="ghcr.io/\${{ github.repository }}:$IMAGE_TAG"
          IMAGE_FULL=$(echo "$IMAGE_FULL" | tr '[:upper:]' '[:lower:]')
          SHA_VAL=\${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

          curl -fsSL -X POST "\${{ secrets.HYLIUS_WEBHOOK_URL }}" \\
            -H "Content-Type: application/json" \\
            -H "Authorization: Bearer \${{ secrets.HYLIUS_API_TOKEN }}" \\
            -H "ngrok-skip-browser-warning: 69420" \\
            -d "{\\"image\\": \\"$IMAGE_FULL\\", \\"sha\\": \\"$SHA_VAL\\", \\"repo\\": \\"\${{ github.repository }}\\", \\"ref\\": \\"\${{ github.ref }}\\", \\"prNumber\\": \\"\${{ github.event.pull_request.number }}\\"}"
`;

const DAGGER_MODULE_JSON = JSON.stringify({
  name: 'hylius-pipeline',
  sdk: 'typescript',
  engineVersion: '0.15.4',
}, null, 2);

const DAGGER_PACKAGE_JSON = JSON.stringify({
  name: 'hylius-pipeline',
  description: 'Hylius CI/CD pipeline powered by Dagger',
  version: '1.0.0',
  main: 'src/index.ts',
  scripts: {},
  dependencies: { '@dagger.io/dagger': '^0.15.4' },
}, null, 2);

const DAGGER_TSCONFIG = JSON.stringify({
  compilerOptions: {
    target: 'ES2020',
    module: 'Node16',
    moduleResolution: 'Node16',
    esModuleInterop: true,
    strict: true,
    outDir: 'dist',
    skipLibCheck: true,
  },
  include: ['src/**/*'],
}, null, 2);

const DAGGER_PIPELINE_TS = `import {
  dag,
  Directory,
  Secret,
  object,
  func,
} from "@dagger.io/dagger";

@object()
export class HyliusPipeline {
  @func()
  async buildAndPush(
    source: Directory,
    registry: string,
    image: string,
    tag: string,
    webhookUrl: string,
    webhookToken: string,
    repo: string,
    sha: string,
    ref: string,
    prNumber: string,
    githubToken: Secret,
  ): Promise<string> {
    const imageFull = \`\${image.toLowerCase()}:\${tag}\`;

    // Build and authenticate with registry
    const built = dag.container()
      .build(source)
      .withRegistryAuth("ghcr.io", "github-actions", githubToken);

    // Push to registry
    const digest = await built.publish(imageFull);

    // Notify Hylius dashboard
    await this.notifyHylius({ webhookUrl, webhookToken, image: imageFull, sha, repo, ref, prNumber });

    return \`Published \${imageFull} @ \${digest}\`;
  }

  private async notifyHylius(opts: {
    webhookUrl: string;
    webhookToken: string;
    image: string;
    sha: string;
    repo: string;
    ref: string;
    prNumber: string;
  }): Promise<void> {
    const payload = JSON.stringify({
      image: opts.image,
      sha: opts.sha,
      repo: opts.repo,
      ref: opts.ref,
      prNumber: opts.prNumber,
    });

    await dag
      .container()
      .from("curlimages/curl:latest")
      .withExec([
        "curl", "-fsSL",
        "-X", "POST", opts.webhookUrl,
        "-H", "Content-Type: application/json",
        "-H", \`Authorization: Bearer \${opts.webhookToken}\`,
        "-d", payload,
      ]).sync();
  }
}
`;

// â”€â”€â”€ Command â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export const ciGenerateCommand = new Command('ci-generate')
  .description('Generate GitHub Actions workflow files for CI/CD deployment')
  .option('--full', 'Generate the full pipeline (setup + deploy) workflow')
  .option('--dagger', 'Generate a Dagger-powered CI pipeline (recommended for GHCR builds)')
  .option('--branch <branch>', 'Target branch for the Dagger workflow', 'main')
  .action(async (options) => {
    console.log(chalk.blue.bold('\nðŸ”§ Hylius CI/CD Workflow Generator\n'));

    // â”€â”€ Dagger mode â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    if (options.dagger) {
      const branch: string = options.branch;
      const files = [
        { rel: `.github/workflows/hylius-dagger.yml`, content: DAGGER_WORKFLOW_YAML(branch) },
        { rel: `.dagger/dagger.json`,                 content: DAGGER_MODULE_JSON },
        { rel: `.dagger/src/index.ts`,                content: DAGGER_PIPELINE_TS },
        { rel: `.dagger/tsconfig.json`,               content: DAGGER_TSCONFIG },
        { rel: `.dagger/package.json`,                content: DAGGER_PACKAGE_JSON },
      ];

      for (const f of files) {
        const absPath = path.join(process.cwd(), f.rel);
        if (fs.existsSync(absPath)) {
          const { overwrite } = await inquirer.prompt([{
            type: 'confirm',
            name: 'overwrite',
            message: `${f.rel} already exists. Overwrite?`,
            default: false,
          }]);
          if (!overwrite) continue;
        }
        fs.mkdirSync(path.dirname(absPath), { recursive: true });
        fs.writeFileSync(absPath, f.content, 'utf-8');
        console.log(chalk.green(`  âœ… Created ${f.rel}`));
      }

      console.log(chalk.cyan.bold('\nðŸ“‹ Next Steps:\n'));
      console.log(chalk.white('  1. Commit and push the generated files'));
      console.log(chalk.white('  2. Go to your GitHub repo â†’ Settings â†’ Secrets and variables â†’ Actions'));
      console.log(chalk.white('  3. Add the following repository secrets:\n'));
      console.log(`     ${chalk.yellow('HYLIUS_WEBHOOK_URL')}  ${chalk.dim('Your Hylius dashboard webhook URL')}`);
      console.log(`     ${chalk.yellow('HYLIUS_API_TOKEN')}    ${chalk.dim('Your Hylius API token')}\n`);
      console.log(chalk.green('  Once secrets are set, every push to ') + chalk.white.bold(branch) + chalk.green(' will auto-build with Dagger and deploy! âš¡\n'));

      console.log(chalk.yellow.bold('  [TIP] Nixpacks 403 Forbidden Error'));
      console.log(chalk.gray('  If your site uses a frontend framework and returns 403 after deploy,'));
      console.log(chalk.gray('  consult the Nixpacks documentation (https://nixpacks.com/) to configure the static output.'));

      return;
    }

    // â”€â”€ Legacy raw-YAML mode â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    const workflowDir = path.join(process.cwd(), '.github', 'workflows');

    let workflowType = options.full ? 'Full Pipeline (Setup + Deploy)' : undefined;
    if (!workflowType) {
      const answers = await inquirer.prompt([{
        type: 'list',
        name: 'workflowType',
        message: 'Which workflow template?',
        choices: [
          'Deploy Only (recommended)',
          'Full Pipeline (Setup + Deploy)',
        ],
      }]);
      workflowType = answers.workflowType;
    }

    const isFullPipeline = workflowType!.includes('Full Pipeline');
    const fileName = isFullPipeline ? 'hylius-pipeline.yml' : 'hylius-deploy.yml';
    const content = isFullPipeline ? FULL_PIPELINE_WORKFLOW : DEPLOY_WORKFLOW;
    const filePath = path.join(workflowDir, fileName);

    if (fs.existsSync(filePath)) {
      const { overwrite } = await inquirer.prompt([{
        type: 'confirm',
        name: 'overwrite',
        message: `${fileName} already exists. Overwrite?`,
        default: false,
      }]);
      if (!overwrite) {
        console.log(chalk.yellow('Aborted.'));
        return;
      }
    }

    fs.mkdirSync(workflowDir, { recursive: true });
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(chalk.green(`\nâœ… Created ${chalk.bold(`.github/workflows/${fileName}`)}\n`));

    console.log(chalk.cyan.bold('ðŸ“‹ Next Steps:\n'));
    console.log(chalk.white('  1. Go to your GitHub repo â†’ Settings â†’ Secrets and variables â†’ Actions'));
    console.log(chalk.white('  2. Add the following repository secrets:\n'));

    const secrets = [
      { name: 'HYLIUS_HOST',        desc: 'Your VPS IP address (e.g., 192.168.1.100)',              required: true },
      { name: 'HYLIUS_USER',        desc: 'SSH username (e.g., root)',                               required: true },
      { name: 'HYLIUS_SSH_KEY',     desc: 'Full SSH private key content',                            required: true },
      { name: 'HYLIUS_TARGET_PATH', desc: 'Remote deploy path (e.g., /var/www/my-app)',              required: true },
      { name: 'HYLIUS_REPO_URL',    desc: 'Git repository URL (e.g. https://github.com/u/r.git)',   required: true },
      { name: 'HYLIUS_PASSWORD',    desc: 'SSH password (if not using SSH keys)',                    required: false },
      { name: 'HYLIUS_PORT',        desc: 'SSH port (defaults to 22)',                               required: false },
    ];

    for (const secret of secrets) {
      const tag = secret.required ? chalk.red('REQUIRED') : chalk.dim('optional');
      console.log(`     ${chalk.yellow(secret.name)} [${tag}]`);
      console.log(`     ${chalk.dim(secret.desc)}\n`);
    }

    console.log(chalk.cyan.bold('ðŸ’¡ Tip:'));
    console.log(chalk.white('  To get your SSH key content, run:'));
    console.log(chalk.gray('  cat ~/.ssh/id_rsa'));
    console.log(chalk.white('\n  Then paste the entire output (including BEGIN/END lines) as the HYLIUS_SSH_KEY secret.\n'));
    console.log(chalk.green('  Once configured, every push to ') + chalk.white.bold('main') + chalk.green(' will auto-deploy! ðŸš€\n'));

    console.log(chalk.dim('  ðŸ’¡ Tip: For faster builds with caching, try: hylius ci-generate --dagger\n'));
  });

