import { Command } from 'commander';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { detectProjectType } from '../utils/detect.js';
import { writeConfig, getProjectName } from '../utils/config.js';
import * as templates from '../templates/index.js';

export const initCommand = new Command('init')
  .description('Initialize a new hylius project')
  .option('--skip-docker', "Don't run docker init")
  .option('--skip-ci', "Don't generate GitHub Actions workflow")
  .action(async (options) => {
    console.log(chalk.blue.bold('🔍 Detecting project type...\n'));

    const projectType = detectProjectType();
    if (projectType === 'unknown') {
      console.log(chalk.yellow('⚠️  Could not detect project type automatically.\n'));
    }

    // Run docker init unless skipped
    if (!options.skipDocker) {
      if (projectType !== 'unknown') {
        console.log(chalk.green(`✨ ${capitalize(projectType)} detected. Using hylius optimized setup...\n`));

        const spinner = ora('Generating Docker configuration...').start();
        try {
          generateConfig(projectType);
          spinner.succeed(chalk.green('Docker configuration generated'));
        } catch (error) {
          spinner.fail(chalk.red('Failed to generate config'));
          console.error(chalk.red(error instanceof Error ? error.message : String(error)));
          process.exit(1);
        }
      } else {
        console.log(chalk.cyan('🐳 Running standard docker init...\n'));
        try {
          execSync('docker init', { stdio: 'inherit' });
        } catch (error) {
          console.error(chalk.red('❌ docker init failed'));
          process.exit(1);
        }
      }
    }

    // Generate hylius.yaml
    const spinner = ora('Creating hylius.yaml...').start();
    const config = {
      project_name: getProjectName(),
      type: projectType,
    };
    writeConfig(config);
    spinner.succeed(chalk.green('Created hylius.yaml'));

    // Generate basic GitHub Actions CI
    if (!options.skipCi) {
      const ciSpinner = ora('Creating GitHub Actions workflow...').start();
      const workflowDir = '.github/workflows';
      fs.mkdirSync(workflowDir, { recursive: true });

      const ciContent = `name: CI

on:
  push:
    branches: [ "main" ] # Runs on main
  pull_request:
    branches: [ "main" ] # Runs on PRs targeting main

jobs:
  build-and-push: # Renamed since there are no tests in this specific job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        # Only login if this is NOT a PR (PRs don't have access to secrets usually)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Meta
        # This official action handles tags/labels logic automatically
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: \${{ secrets.DOCKER_USERNAME }}/${getProjectName()}
          tags: |
            # Tag with "latest" only if pushing to main
            type=raw,value=latest,enable=\${{ github.ref == 'format(refs/heads/main)' }}
            # Always tag with the commit SHA
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push only if it's not a PR
          push: \${{ github.event_name != 'pull_request' }}
          # Use the tags generated by the meta step above
          tags: \${{ steps.meta.outputs.tags }}
          labels: \${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
`;

      const ciPath = path.join(workflowDir, 'ci.yaml');
      fs.writeFileSync(ciPath, ciContent, 'utf8');
      ciSpinner.succeed(chalk.green('Created .github/workflows/ci.yaml'));
    }

    console.log(chalk.green.bold('\n🚀 hylius initialization complete!'));
    console.log(chalk.cyan(`\nNext steps:`));
    console.log(chalk.white(`  $ ${chalk.bold('hylius dev')}  ${chalk.dim('# Start development environment')}`));
    console.log(chalk.white(`  $ ${chalk.bold('hylius build')} ${chalk.dim('# Build production image')}\n`));
  });

function capitalize(str: string): string {
  return str.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
}

function generateConfig(projectType: string): void {
  let dockerfile: string;
  let compose: string;
  let dockerignore = templates.nodeDockerignore; // Default ignore list

  const hasPackageLock = fs.existsSync('package-lock.json');
  const hasRequirements = fs.existsSync('requirements.txt');
  const hasGoMod = fs.existsSync('go.mod');
  const hasPom = fs.existsSync('pom.xml');
  const hasComposerLock = fs.existsSync('composer.lock');

  const options = {
    hasLockfile: hasPackageLock || hasRequirements || hasGoMod || hasPom || hasComposerLock,
    projectType
  };

  switch (projectType) {
    case 'vite':
      dockerfile = templates.getViteDockerfile(options);
      compose = templates.viteCompose;
      break;
    case 'next':
      dockerfile = templates.getNextDockerfile(options);
      compose = templates.nextCompose;
      break;
    case 'node':
      dockerfile = templates.getNodeDockerfile(options);
      compose = templates.nodeCompose;
      break;
    case 'python':
      dockerfile = templates.getPythonDockerfile(options);
      compose = templates.pythonCompose;
      break;
    case 'go':
      dockerfile = templates.getGoDockerfile(options);
      compose = templates.goCompose;
      break;
    case 'java':
      dockerfile = templates.getJavaDockerfile(options);
      compose = templates.javaCompose;
      break;
    case 'php':
    case 'laravel-package':
      dockerfile = templates.getPhpDockerfile(options);
      compose = templates.phpCompose;
      break;
    case 'laravel':
      dockerfile = templates.getLaravelDockerfile(options);
      compose = templates.laravelCompose;
      if (!fs.existsSync('docker-entrypoint.sh')) {
        fs.writeFileSync('docker-entrypoint.sh', templates.laravelEntrypoint, 'utf8');
        console.log(chalk.gray(`   Created: docker-entrypoint.sh`));
      }
      break;
    default:
      throw new Error(`Unsupported project type: ${projectType}`);
  }

  fs.writeFileSync('Dockerfile', dockerfile, 'utf8');
  fs.writeFileSync('compose.yaml', compose, 'utf8');
  if (!fs.existsSync('.dockerignore')) {
    fs.writeFileSync('.dockerignore', dockerignore, 'utf8');
  }
  console.log(chalk.gray(`   Created: Dockerfile, compose.yaml`));
}
